
import { FC, ReactElement } from "react"
import { cn } from "@/lib/utils"
import { Textarea } from "./ui/textarea"

type PromptProps = {
  className?: string
}

export const Prompt: FC<PromptProps> = ({ className }): ReactElement => {
  return (
    <div className={cn('flex-1 grid grid-rows-2 gap-4', className)}>
        <Textarea
            className="leading-relaxed resize-none px-4 py-3"
            placeholder="Enter a message to AI..."
        />
        <Textarea
            className="leading-relaxed resize-none px-4 py-3"
            placeholder="Result generated by AI..."
            readOnly
            disabled
        />
    </div>
  )
}
